models/User.php
<?php

namespace app\models;

use Yii;
use yii\data\Sort;
use app\models\Loan;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property int $personal_code
 * @property int $phone
 * @property bool $active
 * @property bool $dead
 * @property string $lang
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email', 'personal_code', 'phone'], 'required'],
            [['first_name', 'last_name', 'email', 'lang'], 'string'],
            [['personal_code', 'phone'], 'default', 'value' => null],
            [['personal_code', 'phone'], 'integer'],
            [['active', 'dead'], 'boolean'],
            ['email', 'email'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'email' => 'Email',
            'personal_code' => 'Personal Code',
            'phone' => 'Phone',
            'active' => 'Active',
            'dead' => 'Dead',
            'lang' => 'Lang',
            'age' => 'Age',
        ];
    }

    /**
     * Calculation method to get user age by personal code
     * 
     * @return integer
     */
    public static function getUserAge($personalCode)
    {
        if (!preg_match('/^\d{11}$/', $personalCode)) {
            return 0;
        }

        $centry = substr($personalCode, 0, 1);
        $year = substr($personalCode, 1, 2);
        $month = substr($personalCode, 3, 2);
        $day = substr($personalCode, 5, 2);

        switch ($centry) {
            case 1:
            case 2:
                $year = '18'.$year;
            case 3:
            case 4:
                $year = '19'.$year;
            case 5:
            case 6:
                $year = '20'.$year;
        }
        
        $birthDate = new \Datetime($year .'-' . $month . '-' . $day);

        $date = new \Datetime();
        
        return $date->diff($birthDate)->y ?? 0;
    }

    /**
     * Check user age is under limitation for a loan or not
     * 
     * @return boolean
     */
    public static function checkUserAgeForLoan($personalCode)
    {
        return self::getUserAge($personalCode) > Loan::AGE_LIMITATION ? true : false;
    }
}

controllers/LoanController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\User;
use app\models\Loan;
use app\models\LoanSearch;
use yii\data\ActiveDataProvider;
use yii\data\Sort;

class LoanController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Display all loans.
     *
     * @return mixed
     */
    public function actionIndex()
    {   
        $loan = new Loan;
        $params = Yii::$app->request->queryParams;
        
        $query = $loan->find();

        $searchModel = new LoanSearch;
        $query = $searchModel->search($query, $params);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 15,
            ],
        ]);

        return $this->render('index', ['listDataProvider' => $dataProvider,
                                        'searchModel' => $searchModel,
                                        'loan' => $loan]);
    }

    /**
     * Display loan by id.
     * 
     * @param $id
     * @return mixed
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Loan::find()->where(['id' => $id]),
        ]);

        return $this->render('view', ['dataProvider' => $dataProvider]);
    }

    /**
     * Eidt loan by id.
     * 
     * @param $id
     * @return mixed
     */
    public function actionEdit($id)
    {
        $loan = Loan::findOne(['id' => $id]);
        $user = new  User;
                
        if (!$user->findOne(['id' => Yii::$app->request->post('Loan')['user_id']]) && Yii::$app->request->post()) {
            return $this->render('edit', ['loan' => $loan, 'error' => 'The specified user id cannot be found.']);
        }

        // Check age limitation
        if (!$user::checkUserAgeForLoan($dataUser->personal_code)) {
            return $this->render('add', ['loan' => $loan, 'error' => 'The user is under 18 age.']);
        }

        if ($loan->load(Yii::$app->request->post()) && $loan->validate()) {
            $loan->save();
            $this->redirect(["loan/view/{$loan->id}"]);
        }

        return $this->render('edit', ['loan' => $loan, 'error' => $loan->errors]);
    }

    /**
     * Create loan.
     *
     * @return mixed
     */
    public function actionAdd()
    {
        $loan = new Loan;
        $user = new User;
        $user_id = null;

        if ($params = Yii::$app->request->queryParams) {
            $user_id = isset($params['user_id']) ? $params['user_id'] : null;
        }

        if (!($dataUser = $user->findOne(['id' => Yii::$app->request->post('Loan')['user_id']])) && Yii::$app->request->post()) {
            return $this->render('add', ['loan' => $loan, 'error' => 'The specified user id cannot be found.']);
        }

        // Check age limitation
        if (Yii::$app->request->post() && !$user::checkUserAgeForLoan($dataUser->personal_code)) {
            return $this->render('add', ['loan' => $loan, 'error' => 'The user is under 18 age.']);
        }
        
        if ($loan->load(Yii::$app->request->post()) && $loan->validate()) {
            $lastId = $loan->find()->orderBy(['id' => SORT_DESC])->one()->id;
            $loan->id = ++$lastId;
            $loan->save();
            $this->redirect(["loan/view/{$loan->id}"]);
        }

        return $this->render('add', ['loan' => $loan, 'user_id' => $user_id, 'error' => $loan->errors]);
    }

    /**
     * Delete loan by id.
     * 
     * @param $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $loan = Loan::findOne(['id' => $id])->delete();

        $this->redirect(['loan/index']);
    }


}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\data\Sort;
use app\models\UserSearch;

class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Display all users.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $user = new User;
        $params = Yii::$app->request->queryParams;
        
        $query = $user->find();

        $searchModel = new UserSearch;
        $query = $searchModel->search($query, $params);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 15,
            ],
        ]);

        return $this->render('index',['listDataProvider' => $dataProvider,
                                      'searchModel' => $searchModel,
                                      'user' => $user]);
    }

    /**
     * Display user by id.
     * 
     * @param $id
     * @return mixed
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find()->where(['id' => $id]),
        ]);

        return $this->render('view', ['dataProvider' => $dataProvider]);
    }

    /**
     * Eidt user by id.
     *
     * @param $id
     * @return mixed
     */
    public function actionEdit($id)
    {
        $user = User::findOne(['id' => $id]);

        if ($user->load(Yii::$app->request->post()) && $user->validate()) {
            $user->save();
            $this->redirect(["user/view/{$user->id}"]);
        }

        return $this->render('edit', ['user' => $user, 'error' => $user->errors]);
    }

    /**
     * Create user.
     *
     * @return mixed
     */
    public function actionAdd()
    {
        $user = new User;
        if ($user->load(Yii::$app->request->post()) && $user->validate()) {
            $lastId = $user->find()->orderBy(['id' => SORT_DESC])->one()->id;
            $user->id = ++$lastId;
            $user->save();
            $this->redirect(["user/view/{$user->id}"]);
        }

        return $this->render('add', ['user' => $user, 'error' => $user->errors]);
    }

    /**
     * Delete user by id.
     *
     * @param $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $user = User::findOne(['id' => $id])->delete();

        $this->redirect(['user/index']);
    }


}

views/user/_indexList.php
<?php
use yii\helpers\Html;
?>
<tbody>
    <tr>
        <td><?= Html::encode($model['id']) ?></td>
        <td><?= Html::encode($model['first_name']) ?></td>
        <td><?= Html::encode($model['last_name']) ?></td>
        <td><?= Html::encode($model['email']) ?></td>
        <td><?= Html::encode($model['personal_code']) ?></td>
        <td><?= Html::encode($model['phone']) ?></td>
        <td><?= Html::encode($model['active']) ?></td>
        <td><?= Html::encode($model['dead']) ?></td>
        <td><?= Html::encode($model['lang']) ?></td>
        <td><?= Html::a('View', ["/user/view/{$model['id']}"], ['class'=>'btn btn-primary']) ?> <?= Html::a('Edit', ["/user/edit/{$model['id']}"], ['class'=>'btn btn-warning']) ?> <?= Html::a('Delete', ["/user/delete/{$model['id']}"], ['class'=>'btn btn-danger']) ?></td>
    </tr>
</tbody>

views/user/add.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Add user';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php if(isset($error)) {
    if (is_array($error)) { 
        foreach ($error as $value) { ?>
            <div class="alert alert-danger" role="alert">
                <p><?= Html::encode($value[0]) ?></p>
            </div>
        <?php } 
        } else { ?> 
        <div class="alert alert-danger" role="alert">
            <p><?= Html::encode($error) ?></p>
        </div>
<?php   }
    } ?>

<?php $form = ActiveForm::begin(); ?>

    <?= $form->field($user, 'first_name') ?>
    <?= $form->field($user, 'last_name') ?>
    <?= $form->field($user, 'email') ?>
    <?= $form->field($user, 'personal_code') ?>
    <?= $form->field($user, 'phone') ?>
    <?= $form->field($user, 'active')->dropDownList(['0' => 'NO', '1' => 'Yes']) ?>
    <?= $form->field($user, 'dead')->dropDownList(['0' => 'NO', '1' => 'Yes']) ?>
    <?= $form->field($user, 'lang') ?>

    <div class="form-group">
        <?= Html::submitButton('Add User', ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>

views/user/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Edit user';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php if(isset($error)) {
    if (is_array($error)) { 
        foreach ($error as $value) { ?>
            <div class="alert alert-danger" role="alert">
                <p><?= Html::encode($value[0]) ?></p>
            </div>
        <?php } 
        } else { ?> 
        <div class="alert alert-danger" role="alert">
            <p><?= Html::encode($error) ?></p>
        </div>
<?php   }
    } ?>

<?php $form = ActiveForm::begin(); ?>

    <?= $form->field($user, 'id')->textInput(['readonly'=> true]) ?>
    <?= $form->field($user, 'first_name') ?>
    <?= $form->field($user, 'last_name') ?>
    <?= $form->field($user, 'email') ?>
    <?= $form->field($user, 'personal_code') ?>
    <?= $form->field($user, 'phone') ?>
    <?= $form->field($user, 'active')->dropDownList(['0' => 'NO', '1' => 'Yes']) ?>
    <?= $form->field($user, 'dead')->dropDownList(['0' => 'NO', '1' => 'Yes']) ?>
    <?= $form->field($user, 'lang') ?>

    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>

views/user/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;

$this->title = 'List of user';
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="table-container">
  <div class="row">
    <div class="col-lg-12">
      
      <div class="row">
          <div class="col-lg-12">
            <h1> Front-end style should be base on this page. </h1>
          </div>
      </div>

      <div class="row">
        
        <div class="col-lg-12"><?= Html::a('<span>Add User</span>', ["/user/add"], ['class'=>'btn btn-primary']) ?></div>

      </div>

      <div class="row">
        <div class="col-lg-12">
          <?php Pjax::begin(); ?>
          <?=

            GridView::widget([
              'tableOptions' => [
                'class' => 'table table-hover table-sm',
              ],
              'dataProvider' => $listDataProvider,
              'filterModel' => $searchModel,
              'columns' => [
                  ['class' => 'yii\grid\SerialColumn'],
                  'id',
                  'first_name',
                  'last_name',
                  'email',
                  'personal_code',
                  'phone',
                  'active:boolean',
                  'dead:boolean',
                  'lang',
                  [
                    'attribute' => 'age',
                    'label' => 'Age',
                    'value' => function ($user) {
                        return $user::getUserAge($user->personal_code);
                    },
                  ],
                  [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{leadAdd} {leadView} {leadEdit} {leadDelete}',
                    'buttons' => [
                        'leadAdd' => function ($url, $user) {
                              $url = Url::to(['loan/add', 'user_id' => $user->getAttribute('id')]);
                              return Html::a('<span>Add a loan to user</span>', $url, ['title' => 'view', 'class' => 'btn btn-success']);
                          },
                          'leadView' => function ($url, $user) {
                              $url = Url::to(['user/view', 'id' => $user->getAttribute('id')]);
                              return Html::a('<span>View</span>', $url, ['title' => 'view', 'class' => 'btn btn-primary']);
                          },
                          'leadEdit' => function ($url, $user) {
                              $url = Url::to(['user/edit', 'id' => $user->getAttribute('id')]);
                              return Html::a('<span>Edit</span>', $url, ['title' => 'update', 'class' => 'btn btn-info']);
                          },
                          'leadDelete' => function ($url, $user) {
                              $url = Url::to(['user/delete', 'id' => $user->getAttribute('id')]);
                              return Html::a('<span>Delete</span>', $url, [
                                  'title' => 'delete',
                                  'class' => 'btn btn-danger',
                                  'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this user?'),
                                  'data-method' => 'post',
                              ]);
                          },
                  ]],
                ],
              ]); ?>

            <?php Pjax::end(); ?>

        </div>
      </div>

  </div>
</div>
  <div class="row">
      <div class="col-lg-12">
        <?= Html::a('<span>Back</span>', '/', ['class' => 'btn btn-default']);?>
      </div>
  </div>

views/user/view.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\ListView;

$this->title = 'View user';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
  <h2>User Veiw</h2>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
        <th>Personal Code</th>
        <th>Phone</th>
        <th>Active</th>
        <th>Dead</th>
        <th>Lang</th>
        <th>Action</th>
      </tr>
    </thead>
    <?= 
    ListView::widget([
        'itemView'  => '_indexList',
        'dataProvider' => $dataProvider,
    ]); 
    ?>
  </table>
</div>
</body>
</html>